# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230627-070548-universal-italic

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "fa"

pipeline:
- name: "WhitespaceTokenizer"
- name: "LanguageModelFeaturizer"
  model_name: "bert"
  model_weights: "HooshvareLab/bert-base-parsbert-uncased"
  model_tokenizer: "HooshvareLab/bert-base-parsbert-uncased"
  fine_tune: true
- name: "CountVectorsFeaturizer"
  analiyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"
  epochs: 100
  constrain_similarities: true
- name: "EntitySynonymMapper"
- name: "ResponseSelector"
  epochs: 100
  constrain_similarities: true

policies:
- name: RulePolicy
